#!/bin/bash

find . -type f -name '*.gif' -exec sh -c 'for file do echo "$(echo "${file%.*}" | tr "[:upper:]" "[:lower:]")"; done' sh {} + | sort -f > sorted_gif_files.txt && cat sorted_gif_files.txt && rm sorted_gif_files.txt

